# This file was generated by GoReleaser. DO NOT EDIT.
class Ether < Formula
  desc "A modern lightweight programming language written in GO."
  homepage "https://github.com/frederic2ec/ether"
  version "0.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/frederic2ec/ether/releases/download/v0.0.1/ether_0.0.1_mac_amd64.tar.gz"
    sha256 "20666554b8891a4e6aa97f2ce8d9e5a23f4ac13853cb1a402f012e086c5dd447"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/frederic2ec/ether/releases/download/v0.0.1/ether_0.0.1_linux_amd64.tar.gz"
      sha256 "52bc341e0a9ea6da053d0ec3d4164f1d35c279c817c53d21ef9728dd0f9c0407"
    end
  end

  def install
    bin.install "ether"
  end
end
